### ISSUE TITLE
您好，有几个问题请教一下

### ISSUE THREAD

**Issue by lwpgit** [xinyiPig/zzx-hikvision-Java-demo#1]
1.保活线程一直没有重启过持久化任务；
2.历史回放海康RTSP协议报错带宽不足，有遇到过吗？
3.云台控制，命令发过去看不到效果。

**Comment by zzx-Pillar** [comment]
前两条没遇到过，可以咨询一下客服，选一个网点打过去（https://www.hikvision.com/cn/server_51.html）

3、要看看你的摄像头是否支持云台控制，给你一个windows版的4200工具，用工具去测一下（官网也有得下载）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lwpgit"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 下午4:47
收件人:&nbsp;"xinyiPig/zzx-hikvision-Java-demo"<zzx-hikvision-Java-demo@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[xinyiPig/zzx-hikvision-Java-demo] 您好，有几个问题请教一下 (#1)





 
1.保活线程一直没有重启过持久化任务；
 2.历史回放海康RTSP协议报错带宽不足，有遇到过吗？
 3.云台控制，命令发过去看不到效果。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

iVMS-4200(V3.2.0.10_C).rar (248.40M, 2020年05月22日 16:52 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=2b36653217cc40c04398431c43660b1f5353560052560d0749505250534b0d025c07480b57040c1d5050070b0000085550525101657c3959327b361f515409004c60561c5748091e55063a714c484b51163658&code=d6e2ef90

**Comment by zzx-Pillar** [comment]
海康技术咨询邮箱&nbsp;<sdk@hikvision.com&gt;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lwpgit"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 下午4:47
收件人:&nbsp;"xinyiPig/zzx-hikvision-Java-demo"<zzx-hikvision-Java-demo@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[xinyiPig/zzx-hikvision-Java-demo] 您好，有几个问题请教一下 (#1)





 
1.保活线程一直没有重启过持久化任务；
 2.历史回放海康RTSP协议报错带宽不足，有遇到过吗？
 3.云台控制，命令发过去看不到效果。
